### PR TITLE
Add the __repr__ methods to the necessary classes.

### PR DESCRIPTION
**Pull request by tae898**
https://github.com/intelligent-systems-course/schnapsen-dev/issues/16

### CODE REVIEW

**Comment by miselico** [comment]
I suggest including the type of the objects in their string representations, and consider using a constructor style, rather than a map where possible. So, in OrderedCardCollection:

```python
    def __repr__(self) -> str:
        return f"OrderedCardCollection({self.cards})"
```

Rather than
```python
    def __repr__(self) -> str:
        return str({"_cards": self._cards})
```

**Comment by tae898** [comment]
>

**Comment by tae898** [comment]
oops sorry. I closed it by accident.

**Comment by tae898** [comment]
> I suggest including the type of the objects in their string representations, and consider using a constructor style, rather than a map where possible. So, in OrderedCardCollection:
> 
> ```python
>     def __repr__(self) -> str:
>         return f"OrderedCardCollection({self.cards})"
> ```
> 
> Rather than
> 
> ```python
>     def __repr__(self) -> str:
>         return str({"_cards": self._cards})
> ```

what do you mean by this? yours throw an error.

**Comment by miselico** [comment]
I didn't try it, there was a mistake in the variable name. I mean to write:
```python
def __repr__(self) -> str:
    return f"OrderedCardCollection({self._cards})"
```

**Comment by miselico** [comment]
Can you also add test code for these?

**Comment by tae898** [comment]
> ```python
> return f"OrderedCardCollection({self._cards})"
> ```

Alright now I get it.
Btw, this wouldn't work for all the `__repr__` methods I've written, since I've also included the class attributes in them, not just the class arguments. For example:

```python
class Foo:

    def __init__(self, arg) -> None:
        self.arg = arg
        self.attribute = "baz"
    
    def repr_michael(self) -> str:
        return f"Foo({self.arg})"

    def repr_tae(self) -> str:
        return str({"arg": self.arg, "attribute": self.attribute})

foo = Foo("bar")
print(foo.repr_michael())
print(foo.repr_tae())
```

```console
Foo(bar)
{'arg': 'bar', 'attribute': 'baz'}
```

**Comment by miselico** [comment]
Can you further fix those which can be fixed?

**Comment by tae898** [comment]
> Can you also add test code for these?

yes!

**Comment by tae898** [comment]
> Can you further fix those which can be fixed?

alright done!

**Comment by miselico** [comment]
Can you change the tests such that they do not print anything. See the examples in  `test_Marriage` and `test_OrderedCardCollection`. The goal is that we do not have to check anything manually.

**Comment by miselico** [comment]
Probably better to use self.asserEquals instead of `assert`, though.

**Comment by tae898** [comment]
> Probably better to use self.asserEquals instead of `assert`, though.

AFAIK, both will do the same. But with the unittests `self.asserEquals` is better since it shows the differences, if there are any.

**Comment by tae898** [comment]
> Can you change the tests such that they do not print anything. See the examples in `test_Marriage` and `test_OrderedCardCollection`. The goal is that we do not have to check anything manually.

Alright!

**Comment by tae898** [comment]
> Can you change the tests such that they do not print anything. See the examples in test_Marriage and test_OrderedCardCollection. The goal is that we do not have to check anything manually.

Done. Btw, as for `def test_GameState(self)`, I can't break down this test into multiple subtests, since the variables are dependent on each other.

**Pull request merged**
